FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
RUN corepack enable
RUN yarn set version berry
RUN yarn install


COPY . .


ENV NODE_ENV development
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true 

EXPOSE 3000

# 개발 서버 실행
CMD ["yarn", "dev"]